### PR TITLE
Fix Intent Collision, Enhance Notifications Appearance, and Refactor Settings & Database Interactions

### PR DESCRIPTION
**Pull request by ifaresse**
## 🔄 Changes Overview

This PR resolves intent action collisions, improves notification handling for friends within the radius, and introduces enhancements to user settings and local database functionality.

---

## 🛠️ Fixes

- **Notifications Intent Action Collision**: Resolved conflicts with intent actions to ensure proper functionality.
- **Notifications appearance**:
  - Launched notifications only when friends are within the radius.
  - Updated the `alreadyNotifiedFriends` list to prevent redundant notifications during execution. This issue was addressed by making the list mutable.

---

### Friends in Radius
- Documented `userFriendsInRadius` for clarity.
- Updated the predicate of `userFriendsInRadius` to include friends at the border of the radius.
- Added radius selection in the settings screen, allowing users to customize their notification preferences.

### Settings Screen
- Fixed the notification switch functionality in `SettingsScreen` using local db.
- Removed the `onNotificationsEnabledChange` attribute from `SettingsScreen` instances in tests.

### Code Cleanup
- Removed `ConfidentialityScreen.kt` and its associated test file `ConfidentialityScreenTest.kt`.

---

## 🧪 Testing

- **`userFriendsInRadius`**: Added tests to verify functionality, including edge cases for friends at the border of the radius.
- **Local Database Interactions**: Tested all functions interacting with the local database to ensure data integrity and proper behavior.

### New settings screen :
image

### Old settings screen :
image
image

### CODE REVIEW

**Review by daliaghosn — CHANGES_REQUESTED** [review]
**Positive Feedback:**
- Enhanced User Experience: The addition of the RadiusSlider component significantly improves the user experience by allowing users to adjust the notification radius directly in the settings screen.
- Code Readability: The new code, particularly the RadiusSlider function, is well-structured and easy to read.
- Effective Use of ViewModel: The changes leverage the UserViewModel to persist user settings, ensuring that the notification status and radius are saved and retrieved effectively.
- Improved Functionality: The PR resolves intent action collisions and refines notifications, enhancing the app's reliability and user satisfaction.
Thorough Testing: The inclusion of tests for the userFriendsInRadius function and local database interactions demonstrates a commitment to maintaining code quality.

**Points of Improvement:**
- Code Duplication: Ensure that similar UI components, like the RadiusSlider, are reused across the app to maintain consistency and reduce code duplication.
- Performance Optimization: Verify that the changes, especially those involving frequent data retrieval from UserViewModel, do not negatively impact the app's performance.
- UI Consistency: Maintain a consistent UI theme across different components. Ensure that the new RadiusSlider aligns with the overall design aesthetics of the app.
- Documentation: Consider adding comments or documentation for the new RadiusSlider component to help future developers understand its purpose and usage.

**Comment by ifaresse** [comment]
> **Positive Feedback:**
> 
> * Enhanced User Experience: The addition of the RadiusSlider component significantly improves the user experience by allowing users to adjust the notification radius directly in the settings screen.
> * Code Readability: The new code, particularly the RadiusSlider function, is well-structured and easy to read.
> * Effective Use of ViewModel: The changes leverage the UserViewModel to persist user settings, ensuring that the notification status and radius are saved and retrieved effectively.
> * Improved Functionality: The PR resolves intent action collisions and refines notifications, enhancing the app's reliability and user satisfaction.
>   Thorough Testing: The inclusion of tests for the userFriendsInRadius function and local database interactions demonstrates a commitment to maintaining code quality.
> 
> **Points of Improvement:**
> 
> * Code Duplication: Ensure that similar UI components, like the RadiusSlider, are reused across the app to maintain consistency and reduce code duplication.
> * Performance Optimization: Verify that the changes, especially those involving frequent data retrieval from UserViewModel, do not negatively impact the app's performance.
> * UI Consistency: Maintain a consistent UI theme across different components. Ensure that the new RadiusSlider aligns with the overall design aesthetics of the app.
> * Documentation: Consider adding comments or documentation for the new RadiusSlider component to help future developers understand its purpose and usage.

First of all thank you for your review, based on your feedback I changed the title color of "Adjust Radius" from purple to black to be more consistent with the app theme and I documented the component "RadiusSlider".
**Setting screen after this change :
image

**Review by DanR2003 — APPROVED** [review]
- The changes added to only launch notifications when friends are in your radius and to prevent redundant notifications were handled properly.

- The deletion of the ConfidentialityScreen is also proper as it wasn't useful anymore to our app ( Deyan added the functionality to chose what friends in your radius can see your location on the map last week)

- Tests are correctly done as well

**Review by daliaghosn — APPROVED** [review]
You have implemented the suggestion.

**Pull request merged**
