### PR TITLE
Crop and compress profile picture in Settings

### PR DESCRIPTION
**Pull request by marinovdeyan**
When users interact with their profile picture in the Settings of the app, they are now able to:

- Crop the picture with UCrop (picture will also be compressed)
- Remove their profile picture (dynamic button only available when they already have a profile picture)
- Change their profile picture

This way, we ensure that the profile pictures are square and fit well into a circle, plus that they are of appropriate size for long term storage.

### CODE REVIEW

**Comment by marinovdeyan** [comment]
If somebody could tell me what is the code that is duplicated and why SonarCloud is marking "new code" as untested, when it's code I haven't written, but that I just merged from main, that would be great...

**Review by DanR2003 — CHANGES_REQUESTED** [review]
- The functionality added by this PR works well:
 When I add / edit my profile picture, I can correctly crop it / reposition it.
 Also, I can delete my profile picture and then the default user picture is correctly   displayed in this case.

- The tests completed look relevant, but try adding more tests and covering more lines of code as the line coverage is quite far from 80% at the moment.

- Also, if possible, try to modularize some of the code more to reduce duplications.

Overall, this is a good PR, the functionality added is useful for our app and works well - just try to add a few more tests to increase the line coverage.

**Comment by marinovdeyan** [comment]
Hi @DanR2003, thanks for your review!

I looked into the results from SonarCloud to understand why the code coverage is low, because I am testing all of the UI features. So it turns out that it's the launcher, cropLauncher and LaunchedEffect(profilePictureUri) blocks in Settings.kt that are not tested. The problem is that these features are linked to UCrop, which is called by the system call that lets you choose an image from your phone. I do not know how to mock this and how to bypass this system call, so I am afraid I simply cannot reach the 80% line coverage target on new code.

I added some more UI tests in order to really make sure that the UI features that I have developed behave correctly, but everything related to UCrop is not really possible to be tested unfortunately, or at least I do not know how to do that.

Regarding the code duplication, I am unsure where it's coming from to be perfectly honest with you. SonarCloud is not showing me the duplicated lines, so I am not sure what is duplicated and therefore how to make the code more modular. When it comes to UI elements, I just added two buttons, the rest of the work was related to updating the UI efficiently and calling UCrop.

**Review by DanR2003 — APPROVED** [review]
I appreciate your effort to add more UI tests.
I also understand that some features may be really difficult to test, and actually bypassing the system calls with the test can be really a nightmare - it was the same for me with the pop-out calendar;).
Regarding, the duplication of code, looking through your report, I also couldn't spot any duplications so the sonar report is quite puzzling, maybe it could be just eronated.
Conisdering everything stated above in our discussions, I think your PR is good to be merged, as the functionality of it is working well and tests have been made as extensively as possible in this scenario.

**Pull request merged**
