### PR TITLE
feat(offline mode) : now retrieves from cache when offline

### PR DESCRIPTION
**Pull request by Sobell13**
### **Overview**

This pull request introduces several enhancements and fixes to the application, focusing on improving location updates, user status management, and image downloading functionalities. The primary changes include:

- **Location Updates:** Improved the handling of location updates in `MainActivity` and added tests for location-related functionalities.
- **User Status Management:** Enhanced methods for retrieving and updating user status in `UserRepository` and `UserViewModel`.
- **Image Downloading:** Improved the image downloading process in `ImageRepositoryFirebaseStorage` with better error handling and timeout management.
- **Comprehensive Testing:** Added unit tests for `MainActivity`, `ImageRepositoryFirebaseStorage`, and `UserRepositoryFirestore` to ensure reliability and correctness.

### **Detailed Changes**

**1. MainActivity Enhancements**

**Added Methods and Changes:**

- **Location Updates:**
  - Updated `MainActivity` to use `MutableStateFlow` for location updates.
  - Added lifecycle-based status updates to ensure user status is accurately reflected.

**Implementation Highlights:**

- **Real-Time Synchronization:** Ensures that location updates are reflected in real-time across the application.
- **Lifecycle Management:** Automatically updates user status based on activity lifecycle events.

**2. UserRepository Enhancements**

**Added Methods:**

- `getUserFriends(uid: String, onSuccess: (List<User>) -> Unit, onFailure: (Exception) -> Unit)`
  - **Purpose:** Retrieves the list of friends for a user.
  - **Functionality:** Fetches friends from the data source and handles success and failure scenarios.

**Implementation Highlights:**

- **Data Consistency:** Ensures that user data is accurately stored and retrieved.
- **Asynchronous Handling:** Manages asynchronous operations effectively with callbacks.

**3. UserViewModel Enhancements**

**Added Methods:**

- `setCurrentUser()`
  - **Purpose:** Initializes the current user in the `UserViewModel`.
  - **Functionality:** Sets up the user data and prepares the ViewModel for use.

**Implementation Highlights:**

- **Seamless Integration:** Bridges the repository layer with the UI by providing reactive streams that the UI can collect and display.
- **Reactive UI Updates:** Ensures that any changes in user data are immediately reflected in the UI.

**4. ImageRepositoryFirebaseStorage Enhancements**

**Added Methods and Changes:**

- **Image Downloading:**
  - Improved error handling and timeout management for image downloads.
  - Added support for mocking in tests to simulate different scenarios.

**Implementation Highlights:**

- **Error Handling:** Provides robust error handling to manage download failures and timeouts.
- **Testing Support:** Enhances testability by allowing mocking of download tasks.

**5. Comprehensive Testing**

**Tests Implemented:**

- **MainActivity Tests:**
  - `updateLocationIsCalled()`
    - **Purpose:** Verifies that the `updateLocation` method is called correctly.
    - **Approach:** Simulates user interaction and checks that location updates are handled.

- **ImageRepositoryFirebaseStorage Tests:**
  - `downloadImageFactoryFileDownloadTaskCancels()`
    - **Purpose:** Tests the cancellation of image download tasks.
    - **Approach:** Mocks download tasks and verifies cancellation handling.

- **UserRepositoryFirestore Tests:**
  - `getUserBlockedFriends_callsDocumentSnapshotToUserList()`
    - **Purpose:** Ensures that the method correctly processes blocked friends.
    - **Approach:** Mocks Firestore interactions and verifies data processing.

### CODE REVIEW

**Review by ifaresse — CHANGES_REQUESTED** [review]
When first starting the app without sign in before it loops infinitely on the overview screen. And the app crash when I go from the Map screen to the overview. 
(gives a java.lang.NullPointerException)

**Comment by Sobell13** [comment]
1. The infinite loop bug I also had was resolved by just recreating a new emulator for me. Tried to recreate it under several conditions, didn't have it again (~20 tries or so).
2. I never a Map bug during all my testings. No added features from this PR involved the Map feature or any related to it. Should probably have a look in the Firebase then.

**Review by ifaresse — COMMENTED** [review]
The offline mode works fine but when the user is already logged when navigating to another screen and coming back to the overview it makes the app crash but beside that and a bit of lag it works well !

**Review by ifaresse — APPROVED** [review]
LGTM

**Comment by Sobell13** [comment]
The bug coming from navigating between any screen and the Overview never occurred to me, on the emulator.
I suggest someone else test in different conditions to better reproduce it and fix it, if it still happens.

**Pull request merged**
