### PR TITLE
Connect markers on map with friends from FireBase, Refresh location

### PR DESCRIPTION
**Pull request by DanR2003**
Markers shown on the map were connected with real users from the friendsList on Firebase.
Location on the map now gets refreshed every 1 min.
Implemented update of current location to FireBase every 15 mins, even when app is not running.

### CODE REVIEW

**Review by noezaabi — APPROVED** [review]
Looks good. Just need to resolve the merge confllict with main.

**Comment by DanR2003** [comment]
- After a lot of work with the help of Deyan and Ilyas on Monday trying to fix a bug of the worker that's updating the location and timestamp, progress has been made: the worker updates these fields every 15 mins but only while the app is running. 
- For the moment, we still didn't figure out how to make it also run in the background when the app is closed. 
- Any help would be welcome.

**Comment by marinovdeyan** [comment]
Worker is now running in the background, even with the app closed or not opened. In order to achieve this, we now save the uid of the user in the SharedPreferences on the storage of the phone. This way, we don't need to sign in every time the app is opened, but we also have access to the last logged in user in the app in order to update its location every 15 minutes in the background (even without having ever started the app after restarting phone!).

Changes implemented in this PR in order to have the worker working:
- user's uid stored in SharedPreferences in phone storage
- UserViewModel modified to schedule worker and update location on Firestore DB
- UserRepositoryFirestore modified to update location on Firestore DB (it was already doing it, but we changed the way it's stored on the DB, for a simpler implementation)
- Updated tests of UserViewModel and UserRepositoryFirestore to fit the new data model

FYI: this is a very big PR, a lot of things have been modified which were essential in order to get the background location update functional. Please review this with caution and critical thinking.

We worked together, me, @DanR2003 and @ifaresse on this PR to deliver a functional feature.

**Review by daliaghosn — APPROVED** [review]
Strengths:
Comprehensive Dependency Management
Utilizing helper classes promotes cleaner repository implementations.
Proper handling of success and failure scenarios in repository methods.
Areas for Improvement:
Avoid using suspend functions like await() outside coroutine contexts. Refactor methods to use asynchronous callbacks.
Replace force unwrapping (!!) with safe calls and provide default values to prevent NullPointerException.
Removed if unused methods.
Add comprehensive documentation and inline comments to improve code understandability.
Break down large PRs into smaller, focused ones to facilitate easier reviews and reduce potential conflicts.

**Pull request merged**
