### PR TITLE
Rework of contacts

### PR DESCRIPTION
**Pull request by noezaabi**
Add possibility to decline friend request, remove friend list screen and add style to the overview, add friends and contact screen

### CODE REVIEW

**Review by DanR2003 — CHANGES_REQUESTED** [review]
- Although the added functionality looks good, the CI is not passing because tests in AddContactScreenTest and OverviewScreenTest are failing. 

- You need to make them work in order to pass the CI

**Review by DanR2003 — CHANGES_REQUESTED** [review]
Screenshot_20241114-202307_Sudden Bump
Screenshot_20241114-202249_Sudden Bump

- As we can see in the screenshots above, the Add Contact and Overview screens now look very good and are consistent with the rest of the app and the Figma. Also, the feature of accepting or denying friend requests now works fine.

- However,  the scrolling doesn't work inside the Overview screen, and in some places the code could be cleaner by removing comments.  

After this fixes are done, this PR will be ready for merge.

**Review by DanR2003 — CHANGES_REQUESTED** [review]
Screenshot_20241114-224107_Sudden Bump
Great to see you made the modifications I required.
However, as it can be seen above, the writing is black, as the color of the background, and it is very hard to read.
Can you modify this please?

**Review by DanR2003 — APPROVED** [review]
Screenshot_20241114-231731_Sudden Bump
Great! The screen looks perfect now. LGTM

**Review by sophieur444 — APPROVED** [review]
This PR introduces key improvements to contact management and testing:

Enhanced Tests: Updated tests in AddContactTest.kt and OverviewScreenTest.kt ensure critical UI elements are displayed correctly, improving test coverage and reliability.
User Repository Updates: New methods in UserRepository.kt and UserRepositoryFirestore.kt provide better control over friend request handling.
UI Enhancements: Minor UI updates, such as renaming buttons and setting screen orientation, improve user experience.
Overall, these changes strengthen contact functionality and testing robustness. Great work!

**Pull request merged**
